<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0</Version>

    <!-- NuGet package metadata -->
    <PackageId>danisss9.Lite</PackageId>
    <Authors>danisss9</Authors>
    <Description>Lightweight HTML/CSS/JS rendering engine for Windows.</Description>
    <PackageTags>html;css;javascript;renderer;browser;lite;win32</PackageTags>
    <RepositoryUrl>https://github.com/danisss9/Lite</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Lite.Tests" />
    <InternalsVisibleTo Include="Lite.Conformance" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp.Xml" />
    <ProjectReference Include="..\Lite.QuickJs\Lite.QuickJs.csproj" />
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="AngleSharp.Css" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="System.Text.Encoding.CodePages" />
  </ItemGroup>

</Project>
